<?php
/**
 * Title: FAQ
 * Slug: PediCare-Child-Health-Clinic/faq
 * Categories: PediCare-Child-Health-Clinic, featured
 * Block Types: core/template-part/section
 * Viewport Width: 1360
 */
?>
<!-- wp:cover {"url":"<?php echo esc_url(get_template_directory_uri()); ?>/src/images/hero-joy.jpg","id":20,"dimRatio":20,"overlayColor":"secondary","isUserOverlayColor":true,"minHeight":500,"isDark":false,"className":"hdrbanner-BX PediCare-Child-Health-Clinic-gap-0","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-cover is-light hdrbanner-BX PediCare-Child-Health-Clinic-gap-0" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);min-height:500px">
    <span aria-hidden="true" class="wp-block-cover__background has-secondary-background-color has-background-dim-20 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-20" alt="" src="<?php echo esc_url(get_template_directory_uri()); ?>/src/images/hero-joy.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"bannerInfo","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"},"blockGap":"0","margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained","contentSize":"1360px"}} -->
        <div class="wp-block-group bannerInfo" style="margin-top:0;margin-bottom:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0">
            <!-- wp:post-title {"textAlign":"left","textColor":"blue-dark","fontSize":"x-large"} /-->

            <!-- wp:buttons {"style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
            <div class="wp-block-buttons" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:button {"backgroundColor":"accent-color","textColor":"foreground","style":{"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"fontSize":"l"} -->
                <div class="wp-block-button has-custom-font-size has-l-font-size"><a class="wp-block-button__link has-foreground-color has-accent-color-background-color has-text-color has-background has-link-color wp-element-button">Enquire
                        now &gt;</a></div>
                <!-- /wp:button --></div>
            <!-- /wp:buttons --></div>
        <!-- /wp:group --></div></div>
<!-- /wp:cover -->
<!-- wp:group {"className":"PediCare-Child-Health-Clinic-faqs","style":{"spacing":{"blockGap":"0","padding":{"top":"var:preset|spacing|80","right":"var:preset|spacing|50","bottom":"var:preset|spacing|80","left":"var:preset|spacing|50"}}},"backgroundColor":"light","layout":{"type":"constrained","contentSize":"1360px"}} -->
<div class="wp-block-group PediCare-Child-Health-Clinic-faqs has-light-background-color has-background" style="padding-top:var(--wp--preset--spacing--80);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--80);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"textAlign":"center","style":{"typography":{"textTransform":"capitalize"},"spacing":{"margin":{"top":"0","bottom":"var:preset|spacing|80"}}}} -->
    <h2 class="wp-block-heading has-text-align-center" style="margin-top:0;margin-bottom:var(--wp--preset--spacing--80);text-transform:capitalize">Popular&nbsp;<mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-title-highlight-color">Questions</mark></h2>
    <!-- /wp:heading -->

    <!-- wp:details {"showContent":true,"className":"w-100 PediCare-Child-Health-Clinic-faq-item","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"width":"1px"},"spacing":{"padding":{"right":"var:preset|spacing|30","left":"var:preset|spacing|30","top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"elements":{"link":{"color":{"text":"var:preset|color|blue-dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"blue-dark","fontSize":"m"} -->
    <details class="wp-block-details w-100 PediCare-Child-Health-Clinic-faq-item has-blue-dark-color has-text-color has-link-color has-m-font-size" style="border-width:1px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);font-style:normal;font-weight:700" open><summary>BILLINGS</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontStyle":"normal","fontWeight":"500"}}} -->
        <p style="font-style:normal;font-weight:500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ex eros, ultricies vel odio sit amet, lacinia pretium tellus. Morbi lacinia convallis pellentesque. Nullam fermentum at leo non sagittis. Fusce tincidunt, orci interdum efficitur maximus, orci lorem mollis ligula, luctus porta leo lacus sed quam. Nullam non nisi est. Nunc semper arcu et purus pharetra feugiat. Vestibulum aliquet elit vel nulla fermentum, a sodales nulla bibendum. Morbi pulvinar tincidunt nisi, eu rhoncus nulla vehicula sit amet. Nunc laoreet lorem nec aliquet molestie. Donec tempor facilisis risus ut auctor. Nulla auctor tincidunt tellus, id dapibus ipsum vulputate in. Fusce eu lorem eros. Nulla facilisi. Donec nec fermentum tellus. Ut placerat euismod molestie. Curabitur ac ligula a dui molestie egestas accumsan eget eros.</p>
        <!-- /wp:paragraph --></details>
    <!-- /wp:details -->

    <!-- wp:details {"className":"w-100 PediCare-Child-Health-Clinic-faq-item","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"width":"1px"},"spacing":{"padding":{"right":"var:preset|spacing|30","left":"var:preset|spacing|30","top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"elements":{"link":{"color":{"text":"var:preset|color|blue-dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"blue-dark","fontSize":"m"} -->
    <details class="wp-block-details w-100 PediCare-Child-Health-Clinic-faq-item has-blue-dark-color has-text-color has-link-color has-m-font-size" style="border-width:1px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);font-style:normal;font-weight:700"><summary>BILLINGS</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontStyle":"normal","fontWeight":"500"}}} -->
        <p style="font-style:normal;font-weight:500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ex eros, ultricies vel odio sit amet, lacinia pretium tellus. Morbi lacinia convallis pellentesque. Nullam fermentum at leo non sagittis. Fusce tincidunt, orci interdum efficitur maximus, orci lorem mollis ligula, luctus porta leo lacus sed quam. Nullam non nisi est. Nunc semper arcu et purus pharetra feugiat. Vestibulum aliquet elit vel nulla fermentum, a sodales nulla bibendum. Morbi pulvinar tincidunt nisi, eu rhoncus nulla vehicula sit amet. Nunc laoreet lorem nec aliquet molestie. Donec tempor facilisis risus ut auctor. Nulla auctor tincidunt tellus, id dapibus ipsum vulputate in. Fusce eu lorem eros. Nulla facilisi. Donec nec fermentum tellus. Ut placerat euismod molestie. Curabitur ac ligula a dui molestie egestas accumsan eget eros.</p>
        <!-- /wp:paragraph --></details>
    <!-- /wp:details -->

    <!-- wp:details {"className":"w-100 PediCare-Child-Health-Clinic-faq-item","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"width":"1px"},"spacing":{"padding":{"right":"var:preset|spacing|30","left":"var:preset|spacing|30","top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"elements":{"link":{"color":{"text":"var:preset|color|blue-dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"blue-dark","fontSize":"m"} -->
    <details class="wp-block-details w-100 PediCare-Child-Health-Clinic-faq-item has-blue-dark-color has-text-color has-link-color has-m-font-size" style="border-width:1px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);font-style:normal;font-weight:700"><summary>BILLINGS</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontStyle":"normal","fontWeight":"500"}}} -->
        <p style="font-style:normal;font-weight:500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ex eros, ultricies vel odio sit amet, lacinia pretium tellus. Morbi lacinia convallis pellentesque. Nullam fermentum at leo non sagittis. Fusce tincidunt, orci interdum efficitur maximus, orci lorem mollis ligula, luctus porta leo lacus sed quam. Nullam non nisi est. Nunc semper arcu et purus pharetra feugiat. Vestibulum aliquet elit vel nulla fermentum, a sodales nulla bibendum. Morbi pulvinar tincidunt nisi, eu rhoncus nulla vehicula sit amet. Nunc laoreet lorem nec aliquet molestie. Donec tempor facilisis risus ut auctor. Nulla auctor tincidunt tellus, id dapibus ipsum vulputate in. Fusce eu lorem eros. Nulla facilisi. Donec nec fermentum tellus. Ut placerat euismod molestie. Curabitur ac ligula a dui molestie egestas accumsan eget eros.</p>
        <!-- /wp:paragraph --></details>
    <!-- /wp:details -->

    <!-- wp:details {"className":"w-100 PediCare-Child-Health-Clinic-faq-item","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"width":"1px"},"spacing":{"padding":{"right":"var:preset|spacing|30","left":"var:preset|spacing|30","top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"elements":{"link":{"color":{"text":"var:preset|color|blue-dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"blue-dark","fontSize":"m"} -->
    <details class="wp-block-details w-100 PediCare-Child-Health-Clinic-faq-item has-blue-dark-color has-text-color has-link-color has-m-font-size" style="border-width:1px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);font-style:normal;font-weight:700"><summary>BILLINGS</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"typography":{"fontStyle":"normal","fontWeight":"500"}}} -->
        <p style="font-style:normal;font-weight:500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ex eros, ultricies vel odio sit amet, lacinia pretium tellus. Morbi lacinia convallis pellentesque. Nullam fermentum at leo non sagittis. Fusce tincidunt, orci interdum efficitur maximus, orci lorem mollis ligula, luctus porta leo lacus sed quam. Nullam non nisi est. Nunc semper arcu et purus pharetra feugiat. Vestibulum aliquet elit vel nulla fermentum, a sodales nulla bibendum. Morbi pulvinar tincidunt nisi, eu rhoncus nulla vehicula sit amet. Nunc laoreet lorem nec aliquet molestie. Donec tempor facilisis risus ut auctor. Nulla auctor tincidunt tellus, id dapibus ipsum vulputate in. Fusce eu lorem eros. Nulla facilisi. Donec nec fermentum tellus. Ut placerat euismod molestie. Curabitur ac ligula a dui molestie egestas accumsan eget eros.</p>
        <!-- /wp:paragraph --></details>
    <!-- /wp:details --></div>
<!-- /wp:group -->