name: Deploy to Cloudways via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: herve3x/github-action-sftp-deploy@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          privateKey: ${{ secrets.SFTP_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: ./
          remote_path: ${{ secrets.SFTP_REMOTE }}
