name: 🚀 SFTP Deploy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: 'master_qhtkxxsdcb'
          server: '167.172.56.163'
          ssh_private_key: ${{ secrets.SFTP_KEY }}
          local_path: './'
          remote_path: '/home/master/applications/usxqghxpfm/public_html/wp-content/themes/pedicare-child-health-clinic'
          sftpArgs: '-o ConnectTimeout=5'
