name: 🚀 SFTP Deploy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}  # или privateKey если используешь ключ
          protocol: "sftp"
          port: ${{ secrets.SFTP_PORT }}
          server-dir: ${{ secrets.SFTP_REMOTE }}
          local-dir: "./"  
